# Generated by Django 4.2 on 2023-05-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="redirect",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="prompt",
            name="imageUrl",
            field=models.ImageField(blank=True, default="", upload_to=""),
        ),
        migrations.AlterField(
            model_name="user",
            name="clickEvents",
            field=models.ManyToManyField(
                blank=True, related_name="+", to="base.action"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="impressions",
            field=models.ManyToManyField(
                blank=True, related_name="+", to="base.prompt"
            ),
        ),
    ]
