# Generated by Django 4.2 on 2023-05-04 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_alter_action_redirect_alter_prompt_imageurl_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="prompts",
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField(auto_now=True)),
                ("actions", models.ManyToManyField(related_name="+", to="base.action")),
                (
                    "prompt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="base.prompt",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="messages",
            field=models.ManyToManyField(
                blank=True, related_name="+", to="base.message"
            ),
        ),
    ]
